export const queryKeys = {
  me: ["auth", "me"] as const,
  users: ["users"] as const,
  lakes: ["lakes"] as const,
  regulations: ["regulations"] as const,
  lakeRegulations: ["lakeRegulations"] as const,
  teamMembers: (teamId?: string) => ["teamMembers", teamId ?? "all"] as const,
  competitions: ["competitions"] as const,
  competition: (id: string) => ["competitions", id] as const,
  teams: (competitionId: string) => ["teams", competitionId] as const,
  teamsAll: ["teams", "all"] as const,
  sectors: (competitionId: string) => ["sectors", competitionId] as const,
  stands: (competitionId: string) => ["stands", competitionId] as const,
  standsAll: ["stands", "all"] as const,
  standsLake: (lakeId: string) => ["stands", "lake", lakeId] as const,
  results: (competitionId: string) => ["results", competitionId] as const,
  resultsAll: ["results", "all"] as const,
  weighIns: (competitionId: string) => ["weighIns", competitionId] as const,
  capturesAll: ["captures", "all"] as const,
  prizes: (competitionId: string) => ["prizes", competitionId] as const,
};
